- README.md
Just a simple, stupid button with the DPP Hello World, s.t. it's easier to find.
In theory we could support running also the examples with C code with har.
See: https://github.com/dlang-tour/core-exec/pull/40
> Add run.dlang.io button

- source/dpp/translation/typedef_.d
This fixed a problem of mine (vulkan.h), but I haven't tested it with any other code. As those aliases are for C function pointers I don't think this breaks anything else.
> add @nogc and nothrow to function aliases

- source/dpp/translation/macro_.d
bug #90: sizeof(*a) -> (*a).sizeof instead of  *a.sizeof
> fix bug #90

- examples/stl/app.dpp
- examples/stl/build.sh
- examples/stl/dummy.cpp
- examples/stl/test.cpp
- examples/stl/v.cpp
- examples/stl/v.hpp
- source/dpp/runtime/context.d
- source/dpp/translation/aggregate.d
- source/dpp/translation/translation.d
- source/dpp/translation/typedef_.d
- source/main.d
Implementation is very hackish because I was in a hurry and I also don't really know C++.
This adds the ability to blacklist file paths to be translated by dpp and to blacklist types.  Blacklisted types will be substituted in the translated D code by Opaque!("NameOfType",SizeOfType).  
In examples/stl-opaque there is a script build.sh.  This will build a little demonstration from v.hpp, v.cpp and app.dpp showing that one can successfully wrap a source header including a definition of a type depending on std::vector and then access the underlying data as you would expect.
Where dpp replaces instantiated versions of STL types like Opaque!("vector!(double)",24) then dpp should track these and generate boilerplate like double[] getVector(Opaque!("vector!(double)",24) v) and create any …
> WIP: opaque types

- README.md
- dub.sdl
- source/dpp/runtime/app.d
Fixes issues #80 and #86.
Just a trivial `dub` change and build instructions. The real change is in `libclang`, so please bump its version and update dub dependencies.
Cheers,
Bastiaan.
> Windows support.

- source/dpp/runtime/app.d
Compiling on Linux Gives
```
/usr/bin/ld: .dub/obj/d++.o: in function `_D3dpp7runtime3app__T15translationTextTS3std5stdio4FileZQBjFxSQCiQCh7options7OptionsxAyaZ9__lambda8MFNbNiNeZAya':
/data/development/sccp/sources/dlang/dpp/source/dpp/runtime/app.d:160: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
```
Added a simple replacement to use mkstemp instead (not sure if it is to your liking).
Would have been nice if std.file just had createtmpfile [phobos:PR5788](https://github.com/dlang/phobos/pull/5788) :-)
> [MINOR] Fix tmpnam -> mkstemp warning

- source/dpp/translation/translation.d
- tests/it/issues.d
Includes a test for the issue and a simple 'fix'. Not sure if the fix is the way you would like to go though.
references #168
fixes #168
> Fix issue 168 Macro's using `(__extension__({}))`

- source/dpp/translation/function_.d
- source/dpp/translation/macro_.d
- tests/contract/templates.d
- tests/it/issues.d
- tests/it/package.d
Note it will also require new unit-threaded and libclang
to fully pass.
In a couple cases, I exempted the test since it was not
applicable on the Windows platform, but for the most part,
it was tweaking platform-specific details like object file
name extensions and hacking around a slower filesystem.
The MS headers use literals in the form of, e.g. 255i8, and
that extension needed to be handled as well. Otherwise, fairly
small overall.
I realize some of these are unprincipled hacks, so lemme know if you have better ideas...
> Modifications to make `dub test` pass on Windows

- source/dpp/runtime/options.d
Multiple clang options can be specified like this:
d++ --clang-option "-opt1 param1 -opt2 -opt3"..., instead of prepending --clang-option to every single clang option.
> Allow multiple clang options to be specified more easily

- source/dpp/translation/macro_.d
Encountered this while trying to use d++ on a .dpp file containing the following C macro from linux/kernel.h:
```c
#define u64_to_user_ptr(x) ( \
{ \
typecheck(u64, x); \
(void __user *)(uintptr_t)x; \
} \					
)
```
The issue is that the token spelling is not just ")" for the last closed paren, but "\\" + new line + ")", and we would increase the scanIndex indefinitely, searching for just a ")" token.
This fixes the preprocessing part, where dpp would crash because of a fatal error. Still, compilation of the generated D file might fail in some cases, as the macro expansion could generate invalid D code (even if in C it would be valid).
> Fix bug when a multiline macro could cause a range violation error

- source/dpp/translation/macro_.d
- source/dpp/translation/type/package.d
- tests/it/c/compile/projects.d
pointer extensions seen in the Windows API headers.
> Handle rare multi-character literals and Microsoft

- source/dpp/translation/aggregate.d
- tests/it/issues.d
An example of this bug is shown [here](https://gist.github.com/cbecerescu/9a114bb92b23bd8e275a8eae08c6cc2f). (the issue being the last two accessors in the translated D code).
My understanding is that, previously, we would only go to the sub-sub members of a given anonymous struct or union. But if the nesting level is deeper than that, then we no longer generate the accessors correctly for the deeper levels.
> Handle nested C11 anonymous structs/unions

- source/dpp/translation/aggregate.d
- tests/it/c/compile/collision.d
Previously, in a case like the one below
```c
struct A {
union {
unsigned int version;
char module;
};
};
```
the members themselves would be renamed (to version_ and module_), but the accessor function names would not (they would be auto version(...) and auto module(...)).
> Accessors for members of anonymous records are renamed when the members are keywords

- source/dpp/runtime/context.d
Use std.array.Appender instead of a raw dynamic array for "writing" out the translations.
> Context uses Appender for performance reasons

- source/dpp/runtime/context.d
- tests/it/c/compile/collision.d
Previously, for this case
```c
struct A;
struct B {
struct A* A;
};
struct C {
struct A* A;
};
```
dpp would only rename one of the fields (either the one in B or in C), because the _fieldDeclarations associative array overwrites the already existing (if any) line number with a new one. So it would rename only the field which is contained in the last processed struct.
My solution is changing the value of the associative array from LineNumber to LineNumber[], so that dpp knows of all instances where the field should be renamed.
Also made fixFields correctly rename the accessor functions' name and the field that the accessor functions try to access.
> Made fixFields work better for C11 anon records and deal with multiple structs using the same field name which needs renaming

- source/dpp/translation/aggregate.d
- tests/it/c/compile/struct_.d
Previously, for this code
```c
struct A {
const struct {
int version;
int other;
} version;
};
```
dpp would declare a 'const(\_Anonymous_0) version\_;' field inside struct A, along with accessors for the \_Anonymous\_0 struct (i.e. auto version_()). This would result in name clashes. But, anyway, there is no need to define accessors as we already have a named field through which we can modify (in this case just at initialization, because of the const) the field of type \_Anonymous\_0.
> Don't generate accessor functions when declaring a const anonymous struct as a field

- source/dpp/translation/aggregate.d
- tests/it/c/compile/enum_.d
```d
enum Enum1 { A = 68719476704 }; // Compiles fine in both C and D
enum Enum2 { A = 68719476704, B = 1 }; // Still compiles fine in both C and D
enum Enum3 { B = 1, A = 68719476704 }; // Compiles in C, in D => Error: cannot implicitly convert expression 68719476704L of type long to int
```
In the last case the EnumBaseType is inferred by looking at just the first enum value, which is of type int.
In C, sizeof(enum Enum3) is 8 and sizef(enum Enum1/Enum2) is 4. So changing the EnumBaseType to long if a value from the enum overflows int seems ok to me. I'm not sure if this could impact something else I'm not aware of.
EDIT: The unit test I've added passed locally, but now I see that the AppVeyor build test fails.
> Change EnumBaseType if the enum values overflow int

- source/dpp/translation/aggregate.d
- tests/it/issues.d
The following C struct declaration
```c
struct Bad {
int a : 1;
int b : 1;
struct C *ptr; // C is undeclared
}
```
would be translated in D to
```d
struct Bad
{
import std.bitmanip: bitfields;
align(4);
mixin(bitfields!(
int, "a", 1,
int, "b", 1,
uint, "_padding_0", 6
));
uint, "_padding_1", 8
));
C* ptr;
}
```
The issue is that the bitfields final padding would be added twice:
- for the StructDecl type (we handle bitfields before the skipMember check is done)
- for the actual FieldDecl type
This issue doesn't occur when C is a pre-declared struct, as we will only have a FieldDecl for that line.
> Wrong bitfields paddings are no longer generated if the current member should be skipped

- source/dpp/runtime/context.d
- source/dpp/translation/aggregate.d
- source/dpp/translation/macro_.d
- source/dpp/translation/type/package.d
- source/dpp/translation/typedef_.d
- tests/it/c/compile/projects.d
Solution for an issue that occured in the case below:
```c
struct A {
struct B {
int a;
int c;
} b_obj;
int other;
};
void f(struct B*); // works in C, in D it should be A.B
// Also applicable to field types
```
The f function, when translated, would have the parameter of type B* instead of A.B*.
The solution only applies to C (as C++ has namespaces), to struct, union and enum, at any level of nested aggregates.
The solution is based on an associative array which keeps track of aggregate's spelling and their parent's spelling (as well as the line number in which they appear), so that, in the end, we can go to those lines and modify the parameter type (or field type, depending on the case).
EDIT: Another possible solution could be recording the child-parent aggregates like before, and just …
> Nested aggregates in C are now accessible outside of their parent when translated into D

- source/dpp/translation/variable.d
- tests/it/c/compile/projects.d
Such a case happened as a result of translating linux/include/asm-generic/sections.h, where we have
```c
extern __visible const void __nosave_begin, __nosave_end;
```
Discussed with Edi and Razvan who suggested that this void type could be changed to a pointer type.
> Extern void variables are now translated into extern void* variables

- source/dpp/runtime/app.d
- tests/it/c/compile/projects.d
A quick note: I've not been able to run ci.sh neither before my change nor after. Output:
Error: Error writing '
'
dmd failed with exit code 1.
I've tested locally with roughly the same code I added in the unittest.
> C preprocessor warnings are no longer written to the .d file

- source/dpp/translation/macro_.d
- tests/it/c/compile/projects.d
For a concrete example, see the [GFP_ATOMIC](https://elixir.bootlin.com/linux/latest/source/include/linux/gfp.h#L118) macro definition from the linux kernel, where the attribute '__force' is used with a type cast.
LE: I previously tried to add the condition that tokens[0] should be a macro, but I found out that the macro could have been declared later on. The unit test showcases this: '__force' is defined after being used.
> Perform type casting when the type has macro attributes

- source/dpp/translation/macro_.d
- tests/it/c/compile/extensions.d
For a concrete example, see the [__typecheck](https://elixir.bootlin.com/linux/latest/source/include/linux/kernel.h#L834) macro definition from the linux kernel.
> Perform type casting with typeof

- README.md
The versions were outdated compared to what is currently tested in the CI.
I also noticed that this package uses `libclang` as one of its dependencies. Does this mean that we no longer need to install llvm?
> Update the versions in the readme

- source/dpp/runtime/app.d
- source/dpp/translation/aggregate.d
- source/dpp/translation/docs.d
- source/dpp/translation/enum_.d
- source/dpp/translation/function_.d
- source/dpp/translation/typedef_.d
- source/dpp/translation/variable.d
- tests/it/docs.d
- tests/it/main.d
- tests/test_main.d
Dpp now preserves the documentation which means the editors will show data tips when the bound functions are used. :tada:
Fixes #140 
Preserve the documentation on:
All tests including the new ones pass:
Sample header file:
`test.dpp`
```cpp
#include "./test.hpp"
```
`test.hpp`
```cpp
/** f1 doc */
void f1() {}
// f2 non-doc
void f2() {}
/// f3 doc
void f3() {}
/** variable1 doc */
int variable1 = 1 + 2;
/// variable2 doc
int variable2 = 1 + 2;
// variable3 non-doc
int variable3 = 1 + 2;
/** Struct1 doc */
struct Struct1 {
/** prop1 doc */
int prop1;
/** method1 doc */
void method1();
};
/** Enum1 doc */
enum Enum1 {
/** x doc */
x,
/// y doc
y,
// z non doc
z,
};
/** Type1 doc */
typedef int Type1;
```
The output:
`test.d`
```d
extern(C++)
{
/** Type1 doc */
alias Type1 = int;
/** Enum1 …
```
> Preserve the documentation

- source/dpp/runtime/app.d
- tests/it/c/compile/runtime_args.d
- tests/it/package.d
If `--ignoreMacros` is used, then the file is no longer preprocessed (https://github.com/atilaneves/dpp/blob/master/source/dpp/runtime/app.d#L139-L142). However, the preamble will still contain those two `#define`s, so the `.d` file generated will not compile.
> Add vaArgs only if macros are not ignored

- source/dpp/runtime/context.d
- source/dpp/translation/typedef_.d
- tests/it/c/compile/typedef_.d
A nickname for an anonymous struct might be generated without having to translate the anonymous struct as well (e.g. from a FieldDecl, see test). In such a case, `hasNickname` would return `true` in `translateNonFunction`, so the anonymous struct would never get defined, resulting in a compilation error.
`aggregateIsRemembered` is better check because `rememberAggregate` is only called when an aggregate’s definition gets translated, so it’s exactly what we need.
> Do not translate aggregate definition more than once, but translate it when it’s needed.

- source/dpp/translation/macro_.d
- tests/it/issues.d
Before, only a macro consisting of a single literal would be fixed, now all tokens are.
> Fix #303 - fix all literals in a macro

- source/dpp/clang/package.d
- source/dpp/runtime/context.d
- source/dpp/translation/type/package.d
- source/dpp/translation/variable.d
- tests/it/c/compile/struct_.d
A new version of libclang has changed the spelling of anonymous types from "anonymous" to "unnamed".
> Fix new libclang

- .github/workflows/d.yml
- README.md
- dub.sdl
This fixes Windows CI failures
Also tested on libclang here:
https://github.com/atilaneves/libclang/pull/34
> ci: use setup-cpp to install llvm

- source/dpp/runtime/app.d
- tests/it/issues.d
It is caused by the combination of system include paths and the use of `#include_next` directive in the system headers.
In the [example I shown in the issue](https://github.com/atilaneves/dpp/issues/307#issuecomment-1180561484), the dpp first resolves `stdint.h` to `/usr/lib/llvm-10/lib/clang/10.0.0/include/stdint.h` and tries to expand it.
However, `#include_next <stdint.h>` directive in `/usr/lib/llvm-10/lib/clang/10.0.0/include/stdint.h` accidentally includes the same header and failed to include `/usr/include/stdint.h` (it is intended to be included) due to the include guard.
This request fixes this issue by not to resolve the header path if it is in the system paths or specified include paths.
> Fix #307 - not to resolve include path if possible

- source/dpp/runtime/app.d
It fixes #316 by modifying filtering rule for the output of `cpp -w --comments`.
I'm not sure how to add tests for it because it cannot be reproduced with current Github Actions configuration with `clang-cpp`.
Do you have any idea for it?
> Filter indented preprocessor directives

- source/dpp/runtime/options.d
- tests/it/issues.d
Fix #320
upd: It is necessary to explain why it was done through `TemporaryCPATH` - this is because if we try to use for testing CLI arguments like:
```d
runPreprocessOnly("issue320.dpp", "--include-path="~buildPath(sandbox.sandboxPath, "some/include/path");
```
this leads to that directory will be added as last into include dirs list, and first matching directory will always be root of testing sandbox and thus test always passes as good. So here is need this trick for passing include path directly to compiler
> Fix #320 issue

- source/dpp/runtime/context.d
- source/dpp/translation/macro_.d
- tests/it/issues.d
No longer emits trailing underscore from function definitions if there
exists a macro with the same name when function macros aren't emitted.
Naming unchanged when function macros are emitted, but the macro definition actually calls its method counter-part now.
> Don't try to unclash name if macros aren't emitted

- source/dpp/translation/macro_.d
- tests/it/c/compile/preprocessor.d
- tests/test_main.d
Just makes it easier to reuse the parentheses finding method as well as for checking `\\\n)` kind of tokens.
Also import Token everywhere, since it's ubiquitous in this module.
> refactor macro preprocessor parentheses finder

- source/dpp/translation/macro_.d
- tests/it/issues.d
fix #263
single token string and integer literals are emitted as-is with this, without running through the is(typeof()) check.
Since all integers and strings should be representable in D, they should be fine to be included directly after translation.
> simplify generated D code for literal macros

- source/dpp/translation/macro_.d
- tests/it/issues.d
Only a heuristic, but better wrap more than less here, CTFE will cover
the cases when users need compile time values anyway.
Depends on #336
> wrap #defines accessing runtime info into methods
